-- MySQL Script generated by MySQL Workbench
-- 02/22/17 03:06:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema workers_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema workers_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `workers_db` DEFAULT CHARACTER SET utf8 ;
USE `workers_db` ;

-- -----------------------------------------------------
-- Table `workers_db`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workers_db`.`departments` (
  `id_department` INT NOT NULL AUTO_INCREMENT,
  `department_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_department`),
  UNIQUE INDEX `id_department_UNIQUE` (`id_department` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workers_db`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workers_db`.`employees` (
  `id_employee` INT NOT NULL,
  `name_employee` VARCHAR(45) NOT NULL,
  `id_department` INT NOT NULL,
  PRIMARY KEY (`id_employee`, `id_department`),
  UNIQUE INDEX `id_employee_UNIQUE` (`id_employee` ASC),
  INDEX `fk_employees_departments_idx` (`id_department` ASC),
  CONSTRAINT `fk_employees_departments`
    FOREIGN KEY (`id_department`)
    REFERENCES `workers_db`.`departments` (`id_department`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
