-- MySQL Script generated by MySQL Workbench
-- 02/15/17 14:11:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_bank_web
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_bank_web
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_bank_web` DEFAULT CHARACTER SET utf8 ;
USE `db_bank_web` ;

-- -----------------------------------------------------
-- Table `db_bank_web`.`authority_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bank_web`.`authority_types` (
  `id_authority_type` INT NOT NULL AUTO_INCREMENT,
  `type_title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_authority_type`),
  UNIQUE INDEX `id_authority_type_UNIQUE` (`id_authority_type` ASC),
  UNIQUE INDEX `type_UNIQUE` (`type_title` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bank_web`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bank_web`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `id_authority_type` INT NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  INDEX `_idx` (`id_authority_type` ASC),
  CONSTRAINT ``
    FOREIGN KEY (`id_authority_type`)
    REFERENCES `db_bank_web`.`authority_types` (`id_authority_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bank_web`.`user_profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bank_web`.`user_profiles` (
  `id_user_profile` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `passport_seria` VARCHAR(45) NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_user_profile`),
  UNIQUE INDEX `id_user_profile_UNIQUE` (`id_user_profile` ASC),
  INDEX `fk_user_profile_users1_idx` (`id_user` ASC),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC),
  CONSTRAINT `fk_user_profile_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `db_bank_web`.`users` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bank_web`.`bank_account_states`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bank_web`.`bank_account_states` (
  `id_bank_account_state` INT NOT NULL AUTO_INCREMENT,
  `state_type_title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_bank_account_state`),
  UNIQUE INDEX `id_bank_account_state_UNIQUE` (`id_bank_account_state` ASC),
  UNIQUE INDEX `state_type_UNIQUE` (`state_type_title` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bank_web`.`bank_accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bank_web`.`bank_accounts` (
  `id_bank_account` INT NOT NULL AUTO_INCREMENT,
  `current_balance` INT NOT NULL,
  `id_bank_account_state` INT NOT NULL,
  `id_user_profile` INT NOT NULL,
  PRIMARY KEY (`id_bank_account`),
  UNIQUE INDEX `id_bank_account_UNIQUE` (`id_bank_account` ASC),
  INDEX `fk_bank_accounts_bank_account_states1_idx` (`id_bank_account_state` ASC),
  INDEX `fk_bank_accounts_user_profiles1_idx` (`id_user_profile` ASC),
  CONSTRAINT `fk_bank_accounts_bank_account_states1`
    FOREIGN KEY (`id_bank_account_state`)
    REFERENCES `db_bank_web`.`bank_account_states` (`id_bank_account_state`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bank_accounts_user_profiles1`
    FOREIGN KEY (`id_user_profile`)
    REFERENCES `db_bank_web`.`user_profiles` (`id_user_profile`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bank_web`.`card_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bank_web`.`card_types` (
  `id_card_type` INT NOT NULL AUTO_INCREMENT,
  `card_type_tittle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_card_type`),
  UNIQUE INDEX `id_card_type_UNIQUE` (`id_card_type` ASC),
  UNIQUE INDEX `card_type_UNIQUE` (`card_type_tittle` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bank_web`.`credit_cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bank_web`.`credit_cards` (
  `id_credit_card` INT NOT NULL AUTO_INCREMENT,
  `unique_card_number` VARCHAR(45) NOT NULL,
  `id_bank_account` INT NOT NULL,
  `id_card_type` INT NOT NULL,
  PRIMARY KEY (`id_credit_card`),
  UNIQUE INDEX `id_credit_card_UNIQUE` (`id_credit_card` ASC),
  INDEX `fk_credit_cards_bank_accounts1_idx` (`id_bank_account` ASC),
  INDEX `fk_credit_cards_card_types1_idx` (`id_card_type` ASC),
  UNIQUE INDEX `unique_card_number_UNIQUE` (`unique_card_number` ASC),
  CONSTRAINT `fk_credit_cards_bank_accounts1`
    FOREIGN KEY (`id_bank_account`)
    REFERENCES `db_bank_web`.`bank_accounts` (`id_bank_account`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_credit_cards_card_types1`
    FOREIGN KEY (`id_card_type`)
    REFERENCES `db_bank_web`.`card_types` (`id_card_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
